trigger:
  branches:
    include:
      - ci/cd

pool:
  name: 'Azure Pipelines' # This should match the name of your self-hosted agent pool

steps:
# Initialize and validate for the 'bootstrap' directory
- script: |
    echo "Initializing Terraform..."
    terraform init
    
    echo "Validating Terraform configurations..."
    terraform validate
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
  displayName: 'Init and Validate for bootstrap'

# Plan for the 'bootstrap' directory
- script: |
    echo "Generating Terraform plan..."
    terraform plan -out=bootstrap.tfplan
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
  displayName: 'Terraform Plan for bootstrap'

# Apply the Terraform plan (uncomment this section if you want to apply changes automatically)
# - script: |
#     echo "Applying Terraform plan..."
#     terraform apply bootstrap.tfplan
#   workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
#   displayName: 'Terraform Apply for bootstrap'
