trigger:
  branches:
    include:
      - ci/cd

pool:
  vmImage: 'ubuntu-latest'
  
  variables:
  ARM_SUBSCRIPTION_ID: $(Subscription Id)
  ARM_TENANT_ID: $(Tenant Id)


steps:
# Initialize and validate for the 'bootstrap' directory
- script: |
    terraform init
    terraform validate
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
  displayName: 'Init and Validate for bootstrap'

# Plan for the 'bootstrap' directory
- script: terraform plan -out=bootstrap.tfplan
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
  displayName: 'Terraform Plan for bootstrap'
