trigger:
  branches:
    include:
      - ci/cd

pool:
  vmImage: 'ubuntu-latest'

steps:
# Initialize and validate for the 'bootstrap/terraform' directory
- script: |
    terraform init
    terraform validate
   workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
  displayName: 'Init and Validate for bootstrap/terraform'

# Plan for the 'bootstrap/terraform' directory
- script: terraform plan -out=bootstrap.tfplan
   workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
  displayName: 'Terraform Plan for bootstrap/terraform'
