trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'Terraform'
  displayName: 'Terraform CI/CD'

  steps:
  - checkout: self
    displayName: 'Checkout code'

  - script: |
      terraform init
    displayName: 'Terraform Init'
    workingDirectory: $(Build.SourcesDirectory)/bootstrap

  - script: |
      terraform validate
    displayName: 'Terraform Validate'
    workingDirectory: $(Build.SourcesDirectory)/bootstrap

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'
    workingDirectory: $(Build.SourcesDirectory)/bootstrap
