stages:
  - stage: build
    jobs:
      - job: terraform_init
        steps:
          - checkout: self  # Checks out the repository
          - script: |
              cd bootstrap
              terraform init
            displayName: 'Initialize Terraform and Update Lock File'

      - job: terraform_validate_and_plan
        dependsOn: terraform_init
        steps:
          - checkout: self
          - script: |
              cd bootstrap
              terraform validate
            displayName: 'Validate Terraform Configuration'
          - script: |
              cd bootstrap
              terraform plan
            displayName: 'Generate Terraform Execution Plan'
