trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'Terraform'
  displayName: 'Terraform CI/CD'

  steps:
  - checkout: self
    displayName: 'Checkout code'

  - script: |
      terraform init
    displayName: 'Terraform Init'
    workingDirectory: $(/PracticeAzure/PracticeAzure-1) # Update this path if your Terraform files are in a specific directory.

  - script: |
      terraform validate
    displayName: 'Terraform Validate'
    workingDirectory: $(/PracticeAzure/PracticeAzure-1) # Update this path if needed.

  - script: |
      terraform plan -auto-approve
    displayName: 'Terraform Plan'
    workingDirectory: $(/PracticeAzure/PracticeAzure-1) # Update this path if needed.
    # Be cautious with 'terraform apply -auto-approve' in a CI/CD pipeline. Make sure it's safe to apply changes automatically.
