stages:
  - stage: build
    jobs:
      - job: terraform_validate
        steps:
          - checkout: self  # Checks out the repository
          - script: |
              cd bootstrap
              terraform init -backend=false
            displayName: 'Initialize Terraform'
          - script: |
              cd bootstrap
              terraform validate
            displayName: 'Validate Terraform Configuration'

      - job: terraform_plan
        steps:
          - checkout: self
          - script: |
              cd bootstrap
              terraform plan
            displayName: 'Generate Terraform Execution Plan'
