stages:
  - stage: build
    jobs:
      - job: terraform_validate
        steps:
          - script: terraform init -backend=false
            displayName: 'Initialize Terraform'
          - script: terraform validate
            displayName: 'Validate Terraform Configuration'
