trigger:
  branches:
    include:
      - yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    terraform init
    terraform validate
  workingDirectory: bootstrap
  displayName: 'Terraform Init and Validate'

- script: terraform plan -out=tfplan -var="resource_group_name=$(resourceGroupName)" -var="location=$(location)"
  workingDirectory: bootstrap
  displayName: 'Terraform Plan'
