name: Terraform CI/CD Pipeline

on: [push, pull_request]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - bootstrap
          - dns
          - lb
          - vpc
          - vm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd ${{ matrix.directory }}
          terraform init

      - name: Terraform Plan
        run: |
          cd ${{ matrix.directory }}
          terraform plan
